name: PHPCS check

on: [push]

jobs:
  phpcs:
      name: PHPCS
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Composer update
          run: composer install --prefer-dist --no-progress --no-suggest

        - name: phpcs
          run: vendor/bin/phpcs --standard=PSR2 src tests examples -n
